### PR TITLE
Admin interface

### LINKED ISSUE #105: admin interface
The old system had an admin interface to do various tasks. Many of them are not needed anymore.
It also shared the server code with the student interface code which was probably not a great idea.
In any case, in the short term I need to be able to do:

- [x] Unset late flag
- [x] View student results
- [x] Download marks

In more detail:

1. Unset the late flag for a given student for a collection of problems.
2. Look to see the %age of the problems students have completed (I like to send a congrats message to students who get them all done by early week 1.

Longer term (before the end of semester):
Be able to download the marks to merge in with my overall marks file.

### PR DESCRIPTION
**Pull request by jgat**
This branch (when work is complete) will close #105 by introducing a web-based admin interface. Current progress/plan:
* [x] Save the names/emails of all users who access the system on the server.
* [x] Create a webpage which lists all users and their name/email.
* [x] Admins can see the progress page of any user (cf. #87).
  * [x] Breadcrumbs link back to the admin dashboard.
* [x] Admins can allow/disallow late submissions for a question via the progress page (extends #90).
  * [x] Multiple selection of allow/disallow late (see comment thread below).
* [x] Filtering of users in the admin panel (search by name, userid, email).
* [x] Keep records of users who are enrolled in the current semester (to easily allow filtering out of non-students):
  * [x] Storage/view of a user's enrolment status
  * [x] Filtering students who are enrolled/unenrolled
  * [x] Enrol/unenrol students via the web interface
* [x] Show users' progress summary in a column (number of problems completed).
* [x] Sort columns on each field (id, name, email, enrolment, progress).
* [ ] Mass-upload CSV file of all students enrolled in the course.
* [ ] Export marks to CSV via the web interface.

Less-important work, and possible future work:
* Admin view of progress per problem (instead of progress per user)
* Statistical reporting (graphs of # submissions / # students, # submissions per question, submission times per question)
* Restricted access for certain users (e.g. tutors can view some data, possibly anonymised, but can't edit)
* [x] Ability to remove the "enrolled" bit on all users and/or remove all users from the system (convenience for beginning of future semesters).
* [x] Display progress bars on the progress.py webpage.

Current demo: http://csse1001.uqcloud.net/cgi-bin/_tests/admin.py?enrol_filter=all (Only users in [`admin.ADMINS`](https://github.com/CSSE1001/MyPyTutor/blob/admin_interface/cgi-bin/admin.py#L12) can view)

### CODE REVIEW

**Comment by jgat** [comment]
The following images document the admin interface behaviour for problems past the due date (because there are currently no problems with a due date in the past, I made a test problem, added it, took screenshots, then removed the problem - see d72eac5).

If the student has not submitted, this is shown (regardless of whether the problem is overdue or not):
late_unsubmitted

If the student has submitted late and the "allow late" flag is not on, this is shown:
late_submitted

If the student has submitted late and the allow late flag is on, this is shown:
image

If the student has submitted a problem on time, the admin is unable to set/unset the late flag.

**Comment by pjritee** [comment]
Often a student is sick for a week or so and wants several flags unset. In the old admin interface I would pick a student and it would list all the problems and their status and I could choose some (or all) and it would change from submitted late to OK (for those that were submitted). This was also useful if a student was paranoid about a problem being submitted on time - maybe they though they had stuffed up and didn't believe the 'Show Submissions' info. This happened in the past (but very infrequently).

**Comment by jgat** [comment]
Based on this feedback, I've modified the UI to use a checkbox system with a dropdown menu on the top to apply the action.

Play around with http://csse1001.uqcloud.net/cgi-bin/_tests/progress.py?user=uqprobin for an example (or any other user via http://csse1001.uqcloud.net/cgi-bin/_tests/admin.py).

**Comment by pjritee** [comment]
When I use the uqprobin interface it just shows me my submissions. I need to be first be able to pick a student and then set the flag for problems for that student. Maybe I'm doing something wrong????

**Comment by jgat** [comment]
Yes, the intended process is to first pick a student from the [admin dashboard](http://csse1001.uqcloud.net/cgi-bin/_tests/admin.py), then click on their "View Progress" link, which will take you to that student's submissions. For now, pretend that uqprobin (or any of the tutors) is a student.

**Comment by pjritee** [comment]
Ah - I see - I didn't notice the horizontal scroll.
Can't we have the action and filter on one line (or two) and then the table of users below - that way it doesn't take up so much horizontal real estate. Looks good though.
In fact can't the work you have done on displaying the user status be used for students to do a show submissions (or is that your intent).

**Comment by jgat** [comment]
Hm, maybe there's some weird browser-rendering thing happening that I'm not seeing (unless you're using a mobile phone browser or something - I haven't tested what the layout looks like on phones yet). This is what it looks like for me, and if I shrink the window horizontally, it brings things closer together:

image

image

I've already configured it so that students can use this page to see their submission status (I just haven't linked to it from anywhere) - it originally started as this in issue #87. Here's what the page will look like to students: http://csse1001.uqcloud.net/cgi-bin/_tests/progress.py?noadmin.

**Comment by jgat** [comment]
I've made some minor changes to the layout of bits in browser windows that aren't maximised, which might (or might not) fix the layout issues you were seeing.

**Comment by pjritee** [comment]
Under Chromium on ubuntu I get the same as above but in firefox I get
admin

**Comment by pjritee** [comment]
Shouldn't the action form be part of trhead of the table?

**Comment by pjritee** [comment]
Forget that last comment - I can't see what's happening

**Comment by pjritee** [comment]
This might help - as I reduce the width of firefox I eventually get

admin2

and if I reduce it further I get

admin3

**Comment by jgat** [comment]
Fixed in aee224e (in Firefox for OS X).

**Comment by pjritee** [comment]
I can confirm it's fixed for me as well

**Comment by sapi** [comment]
It might be worth including admin support for #110 (returning the number of times a student has attempted a particular tutorial) in this.

It's also worth noting that exporting marks can build on `get_submissions.py`, which does basically the same thing except from the command line.

**Comment by jgat** [comment]
A brief note, I probably won't get a chance to polish this off myself (unless it goes untouched for more than 3 weeks, or unless there's something that needs my attention tomorrow for at most an hour or two).

Still to do here: 
- fix #116, including shifting `get_submissions_for_user` back into `mpt_cgi.py`.
- resolve merge conflicts
- resolve TODOs, e.g. make only pjr able to access admin features. (In any case, the only explicit action that can be taken is marking/unmarking late submissions, and the current setup logs the username and timestamp of anyone who takes those actions - it just doesn't display the logs anywhere).

At that point, this pull request can be safely merged.

Less priority:
- some sort of "upload a list of known users" feature - the role of this would be simply to enable tracking of any students who have never logged into the system.
  - This can be tied in with the "show only enrolled users" filter to avoid showing non-students who log into the system (e.g. course staff, private tutors, curious people).
  - There are only three necessary fields the import should require: login name (i.e. `sXXXXX`), name (don't care about separating given and family names), and email.
- adding reporting of the number of times students have attempted tutorials (e.g. per student per tutorial, or aggregated per tutorial).
- downloading marks summary in CSV
  - examples of nice formats are `userid,score` (e.g. `uqjgaten,44` to indicate a mark of 44 out of N) or maybe `userid,q1,q2,...` with columns corresponding to each question (e.g. `uqjgaten,1,1,0,1` with 0/1 indicating a valid submission or not).

**Comment by sapi** [comment]
Downloading marks is probably the least urgent of the lot, because of
get_submissions.py

I might have a look at the rest soon; I'm stuck in Brisbane for a few weeks
and don't have much to do. No promises though.

**Comment by sapi** [comment]
Now that semester has started, I think it's important that this branch is live on the server (so that we can automatically enroll students).

I added a hotfix (in d6a706a) which displays results for students who have accounts on the server but have not yet logged in while this branch is live.  That will become unnecessary over time.

I'm going to merge this pull request and raise issues against a specific milestone for the work and improvements which remain to be done.

**Pull request merged**
